### ISSUE TITLE
Dynamic __str__ trick to remove lots of code.

### ISSUE THREAD

**Issue by feliam** [crytic/tealer#14]
Random generic idea. As Instructions/Fields class names seems to match 1:1 with __str_ string in most places.
Consider adding the following to the base classes and override only when necessary. 
```
     def __str__(self):
         return self.__class__.__qualname__.lower()
```

This could be implemented in a metaclass or __new__ if want to avoid the u-perf penalty.

**Comment by S3v3ru5** [comment]
Fixed in PR #26
